version: "2.3"
services:
  testlink:
    image: jouve/testlink:1.9.19
    build: .
    environment:
      DB_TYPE: postgres
      DB_USER: testlink
      DB_PASS: testlink
      DB_HOST: db
      DB_NAME: testlink
    ports:
    - 8080:80
  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_PASSWORD: testlink
      POSTGRES_USER: testlink
      POSTGRES_DB: testlink
    volumes:
    - type: volume
      source: dbdata
      target: /var/lib/postgresql/data
volumes:
  dbdata:
